- cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/ServiceCheckWidget.kt
- cogboard-webapp/src/components/widgets/dialogFields/index.js
- cogboard-webapp/src/components/widgets/types/ServiceCheckWidget.js
- docs/widget-service-check.md
Resolved problems with PUT, POST, request body and response body fragment
Removed conditional display for response status
Updated documentation
> Bugfix/widget serviceCheck

- cogboard-webapp/src/components/Widget/index.js
CLAN6-259 | change selector to one which exists in both production and development environments
> CLAN6-259 | Widget Expanded Content Improvements - bugfix

- cogboard-app/src/main/kotlin/com/cognifide/cogboard/config/model/Board.kt
- cogboard-app/src/main/resources/initData/config.json
- cogboard-app/src/test/resources/board/ui-board-config.json
- cogboard-webapp/src/App.js
- cogboard-webapp/src/components/Board/helpers.js
- cogboard-webapp/src/components/Board/index.js
- cogboard-webapp/src/components/Board/styled.js
- cogboard-webapp/src/components/BoardCard/index.js
- cogboard-webapp/src/components/BoardForm/index.js
- cogboard-webapp/src/components/EditBoard.js
- cogboard-webapp/src/components/MainTemplate/index.js
- cogboard-webapp/src/components/boards/index.js
- cogboard-webapp/src/components/boards/types/IframeBoard.js
- cogboard-webapp/src/components/boards/types/WidgetBoard.js
- cogboard-webapp/src/components/boards/types/styled.js
- cogboard-webapp/src/components/widgets/dialogFields/helpers.js
- cogboard-webapp/src/components/widgets/dialogFields/index.js
- cogboard-webapp/src/components/widgets/types/IframeEmbedWidget/index.js
- cogboard-webapp/src/constants/index.js
- functional/cypress-tests/cypress/support/dashboards.js
- add dashboard types: "WidgetBoard" and "iFrameBoard"
- "iFrameBoard: is full width iFrame only board without possibility of adding widgets to it
> CLAN6-226 | Iframe Dashboard

- cogboard-webapp/src/components/MainTemplate/styled.js
> animate save button

- functional/cypress-tests/cypress/fixtures/Dashboard.js
- functional/cypress-tests/cypress/integration/dashboards.js
- functional/cypress-tests/cypress/support/dashboard.js
- functional/cypress-tests/cypress/support/dashboards.js
Dashboard is now encapsulated in a class in tests
More Object oriented design of tests
---
> Dashboard tests refactored and updated

- cogboard-webapp/src/components/widgets/dialogFields/index.js
- functional/cypress-tests/cypress/integration/credentialsEndpoints.js
See https://github.com/Cognifide/cogboard/issues/244 for details
---
> #244  | Unable to add endpoint

- functional/cypress-tests/cypress/support/widgetAssertions.js
Quick fix for "Jenkins Job can be configured and added by logged in user" Cypress test.
Fix for test failing for some locale configurations.
---
> Regexp fix for Jenkins job automation test (locale)

- functional/cypress-tests/package-lock.json
- functional/cypress-tests/package.json
- gradle/docker.gradle.kts
Bumped Cypress to version 4.0.2
---
> Bumped Cypress local and docker to 4.0.2

- .github/workflows/release-drafter.yml
> Removing unnecessary command from GitHub workflow

- functional/cypress-tests/package.json
> Cypress Updated

- .github/workflows/release-drafter.yml
- gradle.properties
- Setting Version number to 1.0.0
- Updating release drafter so it creates docker artifact with version number
It is time to finally set the version number to 1.0.0
---
> Release v.1.0.0 preparation

- api-mocks/mappings/endpoints-mapping.json
Sonarqube mock endpoints updated.
---
> Bugfix | Sonarqube mocks not working

- gradle.properties
> Release 1.0.5 preparation

- cogboard-webapp/src/components/widgets/types/TextWidget/styled.js
> #302 | Text widget scroll fix

- functional/cypress-tests/package-lock.json
- functional/cypress-tests/package.json
> Updating Cypress Dependencies

- cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/connectionStrategy/SSHConnectionStrategy.kt
- cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/logviewer/LogViewerWidget.kt
Added proper handling of errors to send configuration errors to front end
#420
---
> Added proper exception handling to react to errors #420

- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/index.js
#389
- adapts function to new log template
- simplify code
> #389 | hotfix

- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/LogEntry.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/helpers.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/DateRangePicker/CustomPicker.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/DateRangePicker/helpers.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/DateRangePicker/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/DateRangePicker/styled.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/index.js
Add begin & end date filter
Add clear logs functionality
#383 
#392
---
> #383 #392 | LogViewer date delimiting and log clearing

- cogboard-app/src/main/kotlin/com/cognifide/cogboard/logStorage/Log.kt
- cogboard-app/src/main/kotlin/com/cognifide/cogboard/logStorage/LogStorage.kt
- cogboard-app/src/main/kotlin/com/cognifide/cogboard/logStorage/QuarantineRule.kt
- cogboard-app/src/main/kotlin/com/cognifide/cogboard/ssh/auth/SSHAuthData.kt
- cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/logviewer/LogViewerWidget.kt
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/QuarantineModal/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/index.js
Added filtering logs by quarantine rules.
- When new logs are added, only the ones meeting the rules are added to the database.
- When the quarantine rules are changed, logs not meeting the new rules are deleted from the database.
When there are rules, a log meets the rules when any of the texts in headers are matched by any of the regular expressions in the rules.
#396 
---
> #396 - LogsViewer - managing quarantine configuration

- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/LogEntry.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/helpers.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/styled.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/SearchInput/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/SearchInput/styled.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/index.js
- cogboard-webapp/src/hooks/index.js
- Add logic to searchbar
- Fix LogEntry propTypes error
#385
---
> #385 - LogViewer search bar

- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/LogEntry.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/helpers.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/FilterPicker/helpers.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/FilterPicker/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/logLevels.js
Added logic for filtering logs by log level dropdown
#387 
---
> Added logic for filtering by log level

- cogboard-webapp/package-lock.json
- cogboard-webapp/package.json
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/styled.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/index.js
Add log list virtualization
Also sets up following logs (to be improved)
#436
---
> #436 | log list virtualization

- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/index.js
Changed the way the "Clear logs" button works. It checks for the latest log and applies the time filter based on its date (adding one second).
#443
---
> #443 - LogsViewer - server time zones

- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/FilterPicker/AdvancedFiltersMenu/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/FilterPicker/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/QuarantineModal/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/QuarantineModal/styled.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/index.js
- Moved quarantine button to advanced filters modal
#437
Deleted from old location
Added to advanced filters modal
---
> #437 - Logs Viewer - Moved quarantine button to advanced filters modal

- cogboard-app/src/main/kotlin/com/cognifide/cogboard/CogboardConstants.kt
- cogboard-app/src/main/kotlin/com/cognifide/cogboard/ssh/auth/SSHAuthData.kt
- cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/logviewer/LogViewerWidget.kt
- cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/logviewer/logparser/LogParserStrategyFactory.kt
- cogboard-webapp/src/components/widgets/dialogFields/ParserTypeInput.js
- cogboard-webapp/src/components/widgets/dialogFields/index.js
- cogboard-webapp/src/components/widgets/index.js
- Added drop down in Logs Viewer widget configuration modal for choosing parser to be used
- Adjusted creating parser on backend to new config field
#438
---
> #438 - LogsViewer - Parser choosing

- cogboard-app/src/main/kotlin/com/cognifide/cogboard/logStorage/LogStorage.kt
- cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/logviewer/LogViewerWidget.kt
- cogboard-local-compose.yml
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/QuarantineModal/QuarantineForm.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/QuarantineModal/styled.js
- Added a text informing about the way the quarantine filters work.
- Fixed the way the quarantine works - when the log is matched by any rule, it will be deleted.
- Changed the version of MongoDB to 4. This is because of the CPU of the deployment server not supporting MongoDB 5.
#444
Because the MongoDB version is changed, removal of the contents of the `mnt/mongo` directory may be necessary.
---
> #444 - LogsViewer - quarantine info tooltip

- cogboard-webapp/package.json
- cogboard-webapp/src/App.test.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/LogEntry.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/filterByRegExp.test.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/FilterPicker/AdvancedFiltersMenu/EditFilter.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/FilterPicker/AdvancedFiltersMenu/FilterForm.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/FilterPicker/AdvancedFiltersMenu/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/FilterPicker/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/FilterPicker/styled.js
- functional/cypress-tests/cypress/fixtures/Widgets.js
- functional/cypress-tests/cypress/fixtures/logsViewer.js
- functional/cypress-tests/cypress/integration/logsViewer.js
- functional/cypress-tests/cypress/support/logsViewer/filters.js
- functional/cypress-tests/cypress/support/widget.js
- functional/cypress-tests/cypress/support/widgetAssertions.js
- functional/cypress-tests/cypress/support/widgetDynamicTab.js
Functional and unit tests
#440 
---
> #440 | Logs Viewer tests

- cogboard-app/src/main/kotlin/com/cognifide/cogboard/logStorage/LogController.kt
- cogboard-app/src/main/kotlin/com/cognifide/cogboard/logStorage/LogStorage.kt
- cogboard-app/src/main/kotlin/com/cognifide/cogboard/logStorage/model/Log.kt
- cogboard-app/src/main/kotlin/com/cognifide/cogboard/logStorage/model/LogCollectionConfiguration.kt
- cogboard-app/src/main/kotlin/com/cognifide/cogboard/logStorage/model/LogStorageConfiguration.kt
- cogboard-app/src/main/kotlin/com/cognifide/cogboard/logStorage/model/LogVariableData.kt
- cogboard-app/src/main/kotlin/com/cognifide/cogboard/logStorage/model/QuarantineRule.kt
- cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/connectionStrategy/SSHConnectionStrategy.kt
- cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/logviewer/LogViewerWidget.kt
- cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/logviewer/logparser/LogParserStrategy.kt
- cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/logviewer/logparser/LogParserStrategyFactory.kt
- cogboard-app/src/main/kotlin/com/cognifide/cogboard/widget/type/logviewer/logparser/MockLogParserStrategy.kt
- cogboard-app/src/main/resources/META-INF/services/io.knotx.server.api.handler.RoutingHandlerFactory
- cogboard-local-compose.yml
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/helpers.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/index.js
- cogboard-webapp/src/constants/index.js
- cogboard-webapp/src/utils/fetch.js
- knotx/conf/openapi.yaml
- knotx/conf/routes/operations.conf
Changed the way the logs are fetched. There is a new HTTP endpoint for downloading the initial set of logs. The web socket connection is now used to fetch only the newly added logs.
#450
---
> #450 - LogsViewer - optimize logs fetching from backend 

- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/LogEntry.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/filterByDateSpan.test.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/filterByLevel.test.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/helpers.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/styled.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/DateRangePicker/CustomPicker.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/DateRangePicker/getDateSpan.test.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/FilterPicker/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/logLevels.js
- cogboard-webapp/src/hooks/index.js
- functional/cypress-tests/cypress/fixtures/Widgets.js
- functional/cypress-tests/cypress/fixtures/logsViewer.js
- functional/cypress-tests/cypress/integration/logsViewer.js
- functional/cypress-tests/cypress/support/logsViewer/filters.js
- functional/cypress-tests/cypress/support/widgetDynamicTab.js
- update createWidget() test function (Parser type update)
- add unit tests
- add log level functional tests
- add date span functional tests
- fix no template on init bug
#441
---
> #441 | Logs Viewer other tests

- cogboard-app/src/test/kotlin/com/cognifide/cogboard/logStorage/model/QuarantineRuleTest.kt
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/QuarantineModal/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/helpers.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/index.js
- functional/cypress-tests/cypress/integration/logsViewer.js
- Add working export to file button
- Fix badly displayed reason for quarantine rule
- Fix searchbar tests
- Fix unit quarantine tests
#399 #442 #439 
---
> Add export to file button and tests bugfixes

- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/QuarantineModal/QuarantineForm.js
- cogboard-webapp/src/constants/index.js
Icon in quarantine form now redirects to documentation of LogsViewer widget
#466 
---
> Add button redirecting to documentation from quarantine form

- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/LogEntry.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/TextWithCopyButton.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/styled.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/SearchInput/styled.js
- Add copy button on text hover.
- Fix search bar overlapping text.
---
> LogViewer | copy button

- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/QuarantineModal/QuarantineForm.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/QuarantineModal/styled.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/SearchInput/index.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/index.js
- changed the text in the search field from "Search" sio "Highlight"
- changed the icon on the "Export" button
- added a label in the quarantine edit modal
#476
---
> #476 - LogsViewer - Changes on frontend

- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/TextWithCopyButton.js
- cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/styled.js
Fix copy button on servers without HTTPS protocol.
---
> LogViewer | Fix copy button
